
###  para obtener todos los cursos 
GET  http://localhost:80/api/cargo/

### para obtener un curso en espesifico
GET  http://localhost:80/api/curso/3
### para crear un nuevo curso
POST http://localhost:80/api/cargo/register
Content-Type: application/json

{
  "nombre": "Gerente",
  "imagenUrl": "https://static.vecteezy.com/system/resources/previews/027/935/192/non_2x/happy-middle-aged-business-man-ceo-standing-in-office-arms-crossed-photo.jpg",
  "descripcion": "Gerente de Sistemas"
}



### Actualizar los Cursos 
PUT http://localhost:80/api/curso/update/3
Content-Type: application/json

{
    "nombre": "Gerente",
  "imagenUrl": "https://www.shutterstock.com/image-photo/fashion-face-joy-man-studio-260nw-2472679943.jpg",
  "descripcion": " de sistema"
}
### Eliminar Logicamente

PUT http://localhost:80/api/curso/delete/3
Content-Type: application/json


