### 
GET  http://localhost:80/api/usuario/
### 
POST http://localhost:80/api/usuario/register
Content-Type: application/json

{
  "nombre": "Eduardo",
  "apellido": "Quea Medina",
  "documento": "DNI",
  "numeroDocumento": 45457845,
  "email": "EduardoQuea12@gmail.com",
  "nombreUsuario": "EduCa",
  "password": "321654",
  "idCargo": 3,
  "estado": true
}

### Obtener información del usuario autenticado
GET http://localhost:80/api/usuario/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTczNTAwNzY2MCwiZXhwIjoxNzM1MDE0ODYwfQ.lF3Ed_IS5EWJymeli0q65mX77oyTDwcfRBbGfLxjwa8
