### 
GET  http://localhost:80/api/usuario/
### 
POST http://localhost:80/api/usuario/register
Content-Type: application/json

{
  "nombre": "Jose",
  "apellido": "Arango Llamocca",
  "documento": "DNI",
  "numeroDocumento": 74587451,
  "email": "ArangoLlamocca12@gmail.com",
  "nombreUsuario": "Arangol",
  "password": "123456",
  "idCargo": 1,
  "estado": true
}

### Obtener información del usuario autenticado
GET http://localhost:80/api/usuario/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTczNTAwNzY2MCwiZXhwIjoxNzM1MDE0ODYwfQ.lF3Ed_IS5EWJymeli0q65mX77oyTDwcfRBbGfLxjwa8
